/*
 * TIMER1_config.h
 *
 *  Created on: Apr 2, 2021
 *      Author: 8
 */

#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

/*
 * SET TIMER1 MODE
 */

#define TIMER1_MODE  TIMER1_FAST_PWM_9_BIT_MODE

/*
 * SET TIMER1 PRESCALLER
 */
#define TIMER1_PRESCALLER  TIMER1_8_PRE

/*
 * SET TIMER1 COMPARE MATCH OUTPUT MODE
 */

#define TIMER1_CHA_OCR1_MODE  TIMER1_CLEAR_OC1

#define TIMER1_CHB_OCR1_MODE  TIMER1_CLEAR_OC1

/*
 * SET TIMER1 INTERRUPT
 */
#define TIMER1_INTERRUPT  TIMER1_INT_OVF_IC_BOTH

#define TIMER1_INPUT_CAPTURE_EDGE   INPUT_CAPTURE_RISING_EDGE


#endif /* MCAL_TIMER1_TIMER1_CONFIG_H_ */
